version: '3'
services:

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: sph-db
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - sph-network

  #PHP Service
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: sph/php
    container_name: sph-laravel-app
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./laravel:/var/www/html
      - ./log:/var/log/nginx
      #      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # enable this will disable xdebug
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST} remote_port=${XDEBUG_REMOTE_PORT}
    command: >
      bash -c "cd /var/www/html && composer install --prefer-dist && cp .env.example .env &&
          php artisan migrate --force &&
          /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf"
    networks:
      - sph-network

#Docker Networks
networks:
  sph-network:
    driver: bridge

#Volumes
volumes:
  db_data:
    driver: local
